export const topicsToInitDB = [
  "Artificial Intelligence",
  "Biology",
  "Chemistry",
  "Computer Science",
  "Data Analysis",
  "Design",
  "Economics",
  "Education",
  "Engineering",
  "Environment",
  "Ethics",
  "Finance",
  "Gaming",
  "Geography",
  "History",
  "Languages",
  "Law",
  "Literature",
  "Marketing",
  "Mathematics",
  "Music",
  "Philosophy",
  "Physics",
  "Politics",
  "Psychology",
  "Religion",
  "Social Media",
  "Sports",
  "Statistics",
  "Technology",
  "Web Development",
  "Writing",
  "Anatomy",
  "Astronomy",
  "Astrophysics",
  "Behavioral Science",
  "Business",
  "Communication",
  "Criminology",
  "Cybersecurity",
  "Ecology",
  "Electrical Engineering",
  "Energy",
  "Entrepreneurship",
  "Ethnic Studies",
  "Food",
  "Genetics",
  "Geology",
  "Health",
  "Humanities",
  "International Relations",
  "Journalism",
  "Law Enforcement",
  "Linguistics",
  "Marine Biology",
  "Mechanical Engineering",
  "Meteorology",
  "Microbiology",
  "Military",
  "Neuroscience",
  "Nursing",
  "Oceanography",
  "Paleontology",
  "Photography",
  "Political Science",
  "Agriculture",
  "Anthropology",
  "Archaeology",
  "Architecture",
  "Art History",
  "Astrobiology",
  "Biochemistry",
  "Biography",
  "Botany",
  "Ceramics",
  "Chemical Engineering",
  "Computer Engineering",
  "Construction Management",
  "Cosmology",
  "Cultural Studies",
  "Dance",
  "Drama",
  "Earth",
  "Electronic Engineering",
  "Emergency Management",
  "Ergonomics",
  "Fashion",
  "Film Studies",
  "Art",
  "Forensic",
  "Games",
  "Graphic Design",
  "Human-Computer Interaction",
  "Information Science",
  "Interior Design",
  "Internet of Things",
  "Landscape Architecture",
  "Library Science",
  "Logistics",
  "Machine Learning",
  "Information Systems Management",
  "Manufacturing Engineering",
  "Maritime Studies",
  "Materials Science",
  "Medicine",
  "Mineralogy",
  "Molecular Biology",
  "Museology",
  "Nuclear Engineering",
  "Nutrition",
  "Occupational Therapy",
  "Optics",
  "Orthodontics",
  "Pharmacology",
  "Physical Education",
  "Public Administration",
  "Quantum Mechanics",
  "Real Estate",
  "Robotics",
  "Scenography",
  "Sociology",
  "Software Engineering",
  "Soil Science",
  "Special Education",
  "Speech-Language Pathology",
  "Sustainable Development",
  "Teaching",
  "Theatre",
  "Theology",
  "Tourism",
  "Transportation",
];
